export type ServiceCategory =
  | "carriere"
  | "business"
  | "architecture"
  | "juridique"
  | "traduction"
  | "ao"
  | "academique";

export type ServiceBadge = "Populaire" | "Premium" | "Pack" | "Exclusif" | "Nouveau";

export interface ServiceField {
  key: string;
  label: string;
  type: "text" | "textarea" | "select" | "number";
  options?: string[];
  placeholder?: string;
  hint?: string;
  required?: boolean;
  step: number;
}

export interface ServiceStep {
  number: number;
  title: string;
}

export interface Service {
  id: string;
  category: ServiceCategory;
  title: string;
  description: string;
  priceFcfa: number | null;
  badge?: ServiceBadge;
  icon: string;
  steps: ServiceStep[];
  fields: ServiceField[];
}

export const CATEGORIES: { id: ServiceCategory; label: string }[] = [
  { id: "carriere",      label: "Carrière" },
  { id: "business",     label: "Business" },
  { id: "architecture", label: "Architecture" },
  { id: "juridique",    label: "Juridique" },
  { id: "traduction",   label: "Traduction" },
  { id: "ao",           label: "Appels d'offres" },
  { id: "academique",   label: "Académique" },
];

export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    priceFcfa: 7425,
    docs: 5,
    features: ["5 documents/mois", "PDF uniquement", "Tous services Carrière", "Support email"],
  },
  {
    id: "pro",
    name: "Pro",
    priceFcfa: 18675,
    docs: 20,
    badge: "Populaire",
    features: ["20 documents/mois", "PDF + DOCX + XLSX", "Tous les 24 services", "Support prioritaire", "Historique 6 mois"],
  },
  {
    id: "business",
    name: "Business",
    priceFcfa: 44925,
    docs: 999,
    features: ["Documents illimités", "Tous formats", "Tous les 24 services", "Support dédié", "API access"],
  },
];

export const SERVICES: Service[] = [

  // ─── CARRIÈRE ──────────────────────────────────────────────────────────────
  {
    id: "cv",
    category: "carriere",
    title: "CV Professionnel",
    description: "CV ATS-compatible, structuré et optimisé pour décrocher des entretiens.",
    priceFcfa: 3675,
    badge: "Populaire",
    icon: "FileText",
    steps: [
      { number: 1, title: "Informations personnelles" },
      { number: 2, title: "Objectif & Résumé" },
      { number: 3, title: "Expériences professionnelles" },
      { number: 4, title: "Formation & Certifications" },
      { number: 5, title: "Compétences & Extras" },
    ],
    fields: [
      // Step 1
      { step: 1, key: "full_name",       label: "Nom complet",              type: "text",     required: true },
      { step: 1, key: "email",           label: "Email professionnel",       type: "text",     required: true },
      { step: 1, key: "telephone",       label: "Téléphone / WhatsApp",      type: "text",     required: true },
      { step: 1, key: "ville_pays",      label: "Ville, Pays",               type: "text",     required: true },
      { step: 1, key: "linkedin_url",    label: "URL LinkedIn (si existant)",type: "text",     placeholder: "linkedin.com/in/..." },
      { step: 1, key: "site_portfolio",  label: "Site / Portfolio",          type: "text",     placeholder: "https://..." },
      { step: 1, key: "nationalite",     label: "Nationalité",               type: "text" },
      // Step 2
      { step: 2, key: "poste_vise",      label: "Poste visé",                type: "text",     required: true },
      { step: 2, key: "secteur_vise",    label: "Secteur d'activité visé",   type: "text",     required: true },
      { step: 2, key: "type_contrat",    label: "Type de contrat recherché", type: "select",   options: ["CDI", "CDD", "Freelance", "Stage", "Alternance", "Consultant"] },
      { step: 2, key: "disponibilite",   label: "Disponibilité",             type: "text",     placeholder: "Immédiat / 1 mois / date précise" },
      { step: 2, key: "accroche",        label: "Accroche professionnelle",  type: "textarea", required: true, placeholder: "3-4 phrases décrivant votre valeur unique, votre positionnement..." },
      // Step 3
      { step: 3, key: "exp1_poste",      label: "Expérience 1 — Poste",      type: "text",     required: true },
      { step: 3, key: "exp1_entreprise", label: "Expérience 1 — Entreprise", type: "text",     required: true },
      { step: 3, key: "exp1_dates",      label: "Expérience 1 — Dates",      type: "text",     placeholder: "Jan 2022 – Déc 2023" },
      { step: 3, key: "exp1_missions",   label: "Expérience 1 — Missions & réalisations", type: "textarea", required: true, placeholder: "Vos responsabilités, projets clés, résultats chiffrés..." },
      { step: 3, key: "exp2_poste",      label: "Expérience 2 — Poste",      type: "text" },
      { step: 3, key: "exp2_entreprise", label: "Expérience 2 — Entreprise", type: "text" },
      { step: 3, key: "exp2_dates",      label: "Expérience 2 — Dates",      type: "text" },
      { step: 3, key: "exp2_missions",   label: "Expérience 2 — Missions & réalisations", type: "textarea", placeholder: "Missions, projets, résultats..." },
      { step: 3, key: "exp3_missions",   label: "Expérience 3 (poste / entreprise / dates / missions)", type: "textarea", placeholder: "Synthèse de la 3e expérience si applicable" },
      // Step 4
      { step: 4, key: "formation1",      label: "Formation principale (diplôme, école, dates)", type: "textarea", required: true, placeholder: "Ex: Master Finance, HECM Lomé, 2019-2021" },
      { step: 4, key: "formation2",      label: "Autres formations / diplômes", type: "textarea", placeholder: "Baccalauréat, formations courtes..." },
      { step: 4, key: "certifications",  label: "Certifications & formations en ligne", type: "textarea", placeholder: "Coursera, Google, Microsoft, PMP..." },
      // Step 5
      { step: 5, key: "comp_techniques", label: "Compétences techniques",     type: "textarea", required: true, placeholder: "Logiciels, outils, langages, frameworks..." },
      { step: 5, key: "comp_soft",       label: "Soft skills",                type: "textarea", placeholder: "Leadership, communication, gestion de projet..." },
      { step: 5, key: "langues",         label: "Langues parlées",            type: "textarea", required: true, placeholder: "Français (natif), Anglais (C1), Arabe (B2)..." },
      { step: 5, key: "distinctions",    label: "Prix, distinctions, publications", type: "textarea", placeholder: "Récompenses, articles publiés, conférences..." },
      { step: 5, key: "loisirs",         label: "Loisirs & engagements",      type: "text",     placeholder: "Sport, bénévolat, associatif..." },
    ],
  },

  {
    id: "lettre",
    category: "carriere",
    title: "Lettre de motivation",
    description: "Lettre percutante, adaptée au poste et à l'entreprise ciblée.",
    priceFcfa: 2175,
    badge: "Populaire",
    icon: "Mail",
    steps: [
      { number: 1, title: "Candidat & Cible" },
      { number: 2, title: "Votre profil & atouts" },
      { number: 3, title: "Motivation & Personnalisation" },
    ],
    fields: [
      { step: 1, key: "full_name",         label: "Nom complet",              type: "text",     required: true },
      { step: 1, key: "email",             label: "Email",                    type: "text",     required: true },
      { step: 1, key: "telephone",         label: "Téléphone",                type: "text" },
      { step: 1, key: "poste",             label: "Poste visé",               type: "text",     required: true },
      { step: 1, key: "entreprise_cible",  label: "Entreprise cible",         type: "text",     required: true },
      { step: 1, key: "secteur",           label: "Secteur de l'entreprise",  type: "text" },
      { step: 1, key: "source_offre",      label: "Source de l'offre",        type: "text",     placeholder: "LinkedIn, jobboard, recommandation..." },
      { step: 2, key: "experience_resume", label: "Résumé de votre expérience", type: "textarea", required: true, placeholder: "Votre parcours en 3-4 lignes..." },
      { step: 2, key: "atouts",            label: "Vos 3 atouts principaux pour ce poste", type: "textarea", required: true },
      { step: 2, key: "realisation_cle",   label: "Réalisation clé à valoriser", type: "textarea", placeholder: "Un projet, résultat chiffré, succès concret..." },
      { step: 3, key: "connaissance_entreprise", label: "Ce que vous savez de l'entreprise", type: "textarea", required: true, placeholder: "Valeurs, produits, actualité, culture..." },
      { step: 3, key: "motivation",        label: "Votre motivation profonde pour ce poste", type: "textarea", required: true },
      { step: 3, key: "valeur_ajoutee",    label: "Ce que vous apportez spécifiquement", type: "textarea", placeholder: "Compétence rare, réseau, idée..." },
      { step: 3, key: "ton_souhaite",      label: "Ton souhaité",             type: "select",   options: ["Professionnel classique", "Moderne & dynamique", "Formel & institutionnel", "Créatif"] },
    ],
  },

  {
    id: "linkedin",
    category: "carriere",
    title: "Optimisation LinkedIn",
    description: "Profil LinkedIn optimisé pour attirer recruteurs et clients.",
    priceFcfa: 5925,
    icon: "Linkedin",
    steps: [
      { number: 1, title: "Identité professionnelle" },
      { number: 2, title: "Expériences & Formation" },
      { number: 3, title: "Compétences & Réseau" },
      { number: 4, title: "Objectifs & Contenu" },
    ],
    fields: [
      { step: 1, key: "full_name",           label: "Nom complet",                    type: "text",     required: true },
      { step: 1, key: "titre_professionnel", label: "Titre professionnel souhaité",   type: "text",     required: true, placeholder: "Expert Finance | CFO | Consultant UEMOA" },
      { step: 1, key: "secteur",             label: "Secteur d'activité",             type: "text",     required: true },
      { step: 1, key: "pays_ville",          label: "Localisation",                   type: "text",     required: true },
      { step: 1, key: "about_actuel",        label: "Résumé actuel (si existant)",    type: "textarea", placeholder: "Copiez votre section 'À propos' actuelle..." },
      { step: 2, key: "experiences",         label: "Expériences professionnelles",   type: "textarea", required: true, placeholder: "Pour chaque poste : titre, entreprise, dates, missions, réalisations..." },
      { step: 2, key: "formation",           label: "Formation & diplômes",           type: "textarea", required: true },
      { step: 2, key: "certifications",      label: "Certifications & formations",    type: "textarea" },
      { step: 3, key: "competences_cles",    label: "Top 10 compétences à mettre en avant", type: "textarea", required: true },
      { step: 3, key: "recommandations",     label: "Avez-vous des recommandations LinkedIn ?", type: "select", options: ["Oui, existantes", "Non, je veux des templates à demander", "J'en ai besoin mais je ne sais pas à qui"] },
      { step: 3, key: "type_reseau",         label: "Avec qui voulez-vous vous connecter ?", type: "textarea", placeholder: "Recruteurs RH, investisseurs, clients B2B, pairs..." },
      { step: 4, key: "objectif_linkedin",   label: "Objectif principal LinkedIn",    type: "select",   options: ["Trouver un emploi", "Attirer des clients", "Développer ma visibilité", "Lever des fonds", "Devenir influenceur"], required: true },
      { step: 4, key: "type_contenu",        label: "Type de contenu à publier",      type: "textarea", placeholder: "Articles, posts, témoignages clients, études de cas..." },
      { step: 4, key: "valeur_differenciante",label: "Ce qui vous distingue des autres", type: "textarea", required: true },
    ],
  },

  {
    id: "pack_carriere",
    category: "carriere",
    title: "Pack Carrière Complet",
    description: "CV + Lettre de motivation + Profil LinkedIn optimisé.",
    priceFcfa: 11175,
    badge: "Pack",
    icon: "Package",
    steps: [
      { number: 1, title: "Profil & Contact" },
      { number: 2, title: "Objectif professionnel" },
      { number: 3, title: "Expériences" },
      { number: 4, title: "Formation & Compétences" },
      { number: 5, title: "Poste & Entreprise ciblés" },
      { number: 6, title: "LinkedIn & Personnalisation" },
    ],
    fields: [
      { step: 1, key: "full_name",        label: "Nom complet",                type: "text",     required: true },
      { step: 1, key: "email",            label: "Email",                      type: "text",     required: true },
      { step: 1, key: "telephone",        label: "Téléphone",                  type: "text",     required: true },
      { step: 1, key: "ville_pays",       label: "Ville, Pays",                type: "text",     required: true },
      { step: 1, key: "linkedin_url",     label: "URL LinkedIn",               type: "text" },
      { step: 2, key: "poste_vise",       label: "Poste visé",                 type: "text",     required: true },
      { step: 2, key: "secteur",          label: "Secteur visé",               type: "text",     required: true },
      { step: 2, key: "type_contrat",     label: "Type de contrat",            type: "select",   options: ["CDI", "CDD", "Freelance", "Stage", "Consultant"] },
      { step: 2, key: "accroche",         label: "Votre accroche professionnelle", type: "textarea", required: true },
      { step: 3, key: "exp1",             label: "Expérience 1 (poste, entreprise, dates, missions)", type: "textarea", required: true },
      { step: 3, key: "exp2",             label: "Expérience 2",               type: "textarea" },
      { step: 3, key: "exp3",             label: "Expérience 3",               type: "textarea" },
      { step: 4, key: "formation",        label: "Formation principale",       type: "textarea", required: true },
      { step: 4, key: "certifications",   label: "Certifications",             type: "textarea" },
      { step: 4, key: "competences",      label: "Compétences techniques & soft skills", type: "textarea", required: true },
      { step: 4, key: "langues",          label: "Langues",                    type: "text",     required: true },
      { step: 5, key: "entreprise_cible", label: "Entreprise cible (lettre)", type: "text",     required: true },
      { step: 5, key: "motivation",       label: "Motivation pour ce poste",   type: "textarea", required: true },
      { step: 5, key: "atouts",           label: "Vos 3 atouts pour ce poste", type: "textarea", required: true },
      { step: 6, key: "titre_linkedin",   label: "Titre LinkedIn souhaité",    type: "text",     required: true },
      { step: 6, key: "objectif_linkedin",label: "Objectif LinkedIn",          type: "select",   options: ["Emploi", "Clients", "Visibilité", "Réseau"] },
      { step: 6, key: "valeur_unique",    label: "Ce qui vous distingue",      type: "textarea", required: true },
    ],
  },

  // ─── BUSINESS ──────────────────────────────────────────────────────────────
  {
    id: "bmc",
    category: "business",
    title: "Business Model Canvas",
    description: "Canvas structuré pour valider et présenter votre modèle économique.",
    priceFcfa: 7425,
    icon: "LayoutGrid",
    steps: [
      { number: 1, title: "Projet & Contexte" },
      { number: 2, title: "Clients & Proposition de valeur" },
      { number: 3, title: "Canaux & Relations clients" },
      { number: 4, title: "Ressources, Activités & Finances" },
    ],
    fields: [
      { step: 1, key: "nom_projet",        label: "Nom du projet / entreprise",   type: "text",     required: true },
      { step: 1, key: "secteur",           label: "Secteur d'activité",           type: "text",     required: true },
      { step: 1, key: "pays_marche",       label: "Pays / Marché principal",      type: "text",     required: true },
      { step: 1, key: "description",       label: "Description générale du projet", type: "textarea", required: true },
      { step: 1, key: "stade",             label: "Stade du projet",              type: "select",   options: ["Idée", "Validation", "MVP", "Croissance", "Maturité"] },
      { step: 2, key: "segments_clients",  label: "Segments de clientèle",        type: "textarea", required: true, placeholder: "Qui sont vos clients ? B2B, B2C, tranches d'âge, zones géographiques..." },
      { step: 2, key: "proposition_valeur",label: "Proposition de valeur",        type: "textarea", required: true, placeholder: "Quel problème résolvez-vous ? Quelle valeur unique apportez-vous ?" },
      { step: 2, key: "probleme_resolu",   label: "Problème principal résolu",    type: "textarea", required: true },
      { step: 3, key: "canaux",            label: "Canaux de distribution",       type: "textarea", required: true, placeholder: "Boutique physique, e-commerce, agents, partenaires distributeurs..." },
      { step: 3, key: "relation_clients",  label: "Relation avec les clients",    type: "textarea", placeholder: "Service client, self-service, automatisé, communauté..." },
      { step: 3, key: "acquisition",       label: "Stratégie d'acquisition clients", type: "textarea", placeholder: "Comment trouverez-vous vos clients ?" },
      { step: 4, key: "ressources_cles",   label: "Ressources clés",              type: "textarea", required: true, placeholder: "Humaines, technologiques, financières, physiques, intellectuelles..." },
      { step: 4, key: "activites_cles",    label: "Activités clés",               type: "textarea", required: true, placeholder: "Production, marketing, R&D, logistique..." },
      { step: 4, key: "partenaires",       label: "Partenaires clés",             type: "textarea", placeholder: "Fournisseurs, partenaires stratégiques, sous-traitants..." },
      { step: 4, key: "sources_revenus",   label: "Sources de revenus",           type: "textarea", required: true, placeholder: "Vente directe, abonnement, commission, licence..." },
      { step: 4, key: "structure_couts",   label: "Structure de coûts",           type: "textarea", required: true, placeholder: "Charges fixes, variables, coûts principaux..." },
    ],
  },

  {
    id: "plan_affaire",
    category: "business",
    title: "Plan d'affaires",
    description: "Business plan complet en 10 chapitres, adapté au contexte africain/UEMOA.",
    priceFcfa: 22425,
    badge: "Premium",
    icon: "TrendingUp",
    steps: [
      { number: 1, title: "Présentation de l'entreprise" },
      { number: 2, title: "Étude de marché" },
      { number: 3, title: "Stratégie commerciale" },
      { number: 4, title: "Plan opérationnel" },
      { number: 5, title: "Organisation & RH" },
      { number: 6, title: "Plan financier" },
      { number: 7, title: "Analyse des risques" },
      { number: 8, title: "Contexte & Annexes" },
    ],
    fields: [
      // Step 1
      { step: 1, key: "nom_entreprise",    label: "Nom de l'entreprise",          type: "text",     required: true },
      { step: 1, key: "forme_juridique",   label: "Forme juridique",              type: "select",   options: ["SARL", "SA", "SAS", "EURL", "Auto-entrepreneur", "GIE", "Association"], required: true },
      { step: 1, key: "secteur",           label: "Secteur d'activité",           type: "text",     required: true },
      { step: 1, key: "date_creation",     label: "Date de création prévue",      type: "text",     placeholder: "Janvier 2026 ou déjà créée" },
      { step: 1, key: "siege",             label: "Siège social / Localisation",  type: "text",     required: true },
      { step: 1, key: "description",       label: "Description détaillée du projet", type: "textarea", required: true, placeholder: "Que faites-vous exactement ? Vos produits, services, processus..." },
      { step: 1, key: "vision",            label: "Vision à 5 ans",               type: "textarea", placeholder: "Où voulez-vous être dans 5 ans ?" },
      { step: 1, key: "mission",           label: "Mission de l'entreprise",      type: "textarea" },
      // Step 2
      { step: 2, key: "marche_cible",      label: "Marché cible & zone géographique", type: "textarea", required: true },
      { step: 2, key: "taille_marche",     label: "Taille du marché (estimée)",   type: "text",     placeholder: "Ex: 500 000 ménages urbains au Togo" },
      { step: 2, key: "concurrents",       label: "Principaux concurrents",       type: "textarea", required: true, placeholder: "Nommez-les et décrivez leurs forces/faiblesses" },
      { step: 2, key: "avantage_concurrentiel", label: "Votre avantage concurrentiel", type: "textarea", required: true },
      { step: 2, key: "swot",              label: "SWOT (forces, faiblesses, opportunités, menaces)", type: "textarea", placeholder: "Listez les éléments clés de votre SWOT..." },
      // Step 3
      { step: 3, key: "produits_services", label: "Produits / Services en détail", type: "textarea", required: true, placeholder: "Décrivez chaque offre, ses caractéristiques, son prix..." },
      { step: 3, key: "politique_prix",    label: "Politique de prix",            type: "textarea", required: true, placeholder: "Comment fixez-vous vos prix ? Marges prévues ?" },
      { step: 3, key: "canaux_distribution",label: "Canaux de distribution",     type: "textarea", required: true },
      { step: 3, key: "strategie_comm",    label: "Stratégie de communication",   type: "textarea", placeholder: "Réseaux sociaux, bouche à oreille, publicité, événements..." },
      { step: 3, key: "objectifs_ventes",  label: "Objectifs de ventes An 1",     type: "textarea", required: true, placeholder: "Nombre de clients, CA cible, parts de marché..." },
      // Step 4
      { step: 4, key: "processus_production",label: "Processus de production / prestation", type: "textarea", required: true, placeholder: "Comment créez-vous et livrez-vous votre produit/service ?" },
      { step: 4, key: "fournisseurs",      label: "Principaux fournisseurs",      type: "textarea", placeholder: "Matières premières, logistique, sous-traitants..." },
      { step: 4, key: "localisation_operationnelle", label: "Locaux / Infrastructure", type: "textarea", placeholder: "Bureau, atelier, entrepôt, surface, loyer..." },
      { step: 4, key: "equipements",       label: "Équipements nécessaires",      type: "textarea", placeholder: "Liste + coût estimé de chaque équipement" },
      // Step 5
      { step: 5, key: "equipe_fondateurs", label: "Équipe fondatrice",            type: "textarea", required: true, placeholder: "Prénom, rôle, expérience, compétences clés de chaque fondateur..." },
      { step: 5, key: "effectif_prevu",    label: "Effectif prévu (An 1 → An 3)", type: "textarea", placeholder: "Ex: An 1: 3 personnes, An 2: 6 personnes..." },
      { step: 5, key: "postes_cles",       label: "Postes clés à recruter",       type: "textarea", placeholder: "Intitulé du poste, profil, salaire mensuel prévu..." },
      // Step 6
      { step: 6, key: "investissement",    label: "Investissement initial total (FCFA)", type: "text", required: true },
      { step: 6, key: "detail_investissement", label: "Détail des investissements",type: "textarea", required: true, placeholder: "Équipements X FCFA, travaux Y FCFA, fonds de roulement Z FCFA..." },
      { step: 6, key: "financement",       label: "Sources de financement",       type: "textarea", required: true, placeholder: "Apport personnel, prêt bancaire, investisseur, subvention..." },
      { step: 6, key: "ca_an1",            label: "CA prévisionnel An 1 (FCFA)", type: "text",     required: true },
      { step: 6, key: "ca_an2",            label: "CA prévisionnel An 2 (FCFA)", type: "text" },
      { step: 6, key: "ca_an3",            label: "CA prévisionnel An 3 (FCFA)", type: "text" },
      { step: 6, key: "charges_fixes",     label: "Charges fixes mensuelles",     type: "text",     placeholder: "Loyer, salaires, abonnements..." },
      { step: 6, key: "charges_variables", label: "Charges variables principales",type: "textarea", placeholder: "Matières premières, commissions, livraison..." },
      // Step 7
      { step: 7, key: "risques_identifies",label: "Risques identifiés",          type: "textarea", required: true, placeholder: "Risques de marché, opérationnels, financiers, réglementaires..." },
      { step: 7, key: "plan_mitigation",   label: "Plan de mitigation des risques", type: "textarea", placeholder: "Comment allez-vous gérer chaque risque ?" },
      // Step 8
      { step: 8, key: "pays",              label: "Pays / Zone monétaire",        type: "text",     required: true, placeholder: "Togo, Côte d'Ivoire, Sénégal, UEMOA..." },
      { step: 8, key: "contexte_reglementaire", label: "Contexte réglementaire particulier", type: "textarea", placeholder: "Licences requises, réglementations sectorielles..." },
      { step: 8, key: "impact_social",     label: "Impact social & environnemental", type: "textarea", placeholder: "Emplois créés, impact ESG, RSE..." },
      { step: 8, key: "infos_complementaires", label: "Informations complémentaires", type: "textarea", placeholder: "Tout ce qui n'a pas été couvert et qui est important..." },
    ],
  },

  {
    id: "pitch",
    category: "business",
    title: "Pitch Deck",
    description: "Deck investisseur percutant pour lever des fonds.",
    priceFcfa: 18675,
    badge: "Premium",
    icon: "Presentation",
    steps: [
      { number: 1, title: "Présentation startup" },
      { number: 2, title: "Problème & Solution" },
      { number: 3, title: "Marché & Concurrence" },
      { number: 4, title: "Modèle économique" },
      { number: 5, title: "Équipe & Traction" },
      { number: 6, title: "Besoins en financement" },
    ],
    fields: [
      { step: 1, key: "nom_startup",       label: "Nom de la startup",            type: "text",     required: true },
      { step: 1, key: "secteur",           label: "Secteur / Vertical",           type: "text",     required: true },
      { step: 1, key: "pays",              label: "Pays / Marché principal",       type: "text",     required: true },
      { step: 1, key: "stade",             label: "Stade de développement",       type: "select",   options: ["Pré-seed", "Seed", "Série A", "Série B", "Croissance"], required: true },
      { step: 1, key: "one_liner",         label: "One-liner (pitch en 1 phrase)", type: "text",     required: true, placeholder: "Nous sommes le [Uber/Airbnb] du [secteur] en [zone]" },
      { step: 2, key: "probleme",          label: "Problème résolu",              type: "textarea", required: true, placeholder: "Décrivez le problème avec des données, exemples concrets..." },
      { step: 2, key: "taille_probleme",   label: "Ampleur du problème",          type: "textarea", placeholder: "Combien de personnes sont touchées ? Quel coût économique ?" },
      { step: 2, key: "solution",          label: "Votre solution",               type: "textarea", required: true, placeholder: "Comment résolvez-vous ce problème ? En quoi êtes-vous unique ?" },
      { step: 2, key: "demo",              label: "Démo / Produit existant",      type: "textarea", placeholder: "Décrivez votre MVP, prototype, ou version actuelle..." },
      { step: 3, key: "tam",               label: "TAM — Marché total adressable", type: "text",    required: true, placeholder: "Ex: 2 milliards USD" },
      { step: 3, key: "sam",               label: "SAM — Marché accessible",      type: "text",     placeholder: "Ex: 300M USD en Afrique de l'Ouest" },
      { step: 3, key: "som",               label: "SOM — Part réalisable (5 ans)",type: "text",     placeholder: "Ex: 30M USD" },
      { step: 3, key: "concurrents",       label: "Concurrents & alternatives",   type: "textarea", required: true, placeholder: "Directs, indirects, substituts. Leur positionnement vs le vôtre." },
      { step: 3, key: "avantage",          label: "Avantage compétitif durable",  type: "textarea", required: true },
      { step: 4, key: "modele_revenus",    label: "Modèle de revenus",            type: "textarea", required: true, placeholder: "Abonnement, commission, freemium, B2B SaaS, transaction..." },
      { step: 4, key: "prix",              label: "Structure de prix",            type: "textarea", required: true, placeholder: "Prix de vente, marges, LTV client, CAC..." },
      { step: 4, key: "projection_ca",     label: "Projection CA (3 ans)",        type: "textarea", placeholder: "An 1: X FCFA, An 2: Y FCFA, An 3: Z FCFA" },
      { step: 5, key: "equipe",            label: "Équipe fondatrice",            type: "textarea", required: true, placeholder: "Nom, rôle, expérience clé, pourquoi cette personne ?" },
      { step: 5, key: "traction",          label: "Traction actuelle",            type: "textarea", required: true, placeholder: "Clients, revenus, utilisateurs, MoM growth, partenariats..." },
      { step: 5, key: "milestones",        label: "Milestones atteints",          type: "textarea", placeholder: "Dates et étapes clés franchies..." },
      { step: 6, key: "montant_levee",     label: "Montant à lever",              type: "text",     required: true, placeholder: "Ex: 500 000 USD" },
      { step: 6, key: "use_of_funds",      label: "Utilisation des fonds",        type: "textarea", required: true, placeholder: "40% tech, 30% commercial, 30% opérations..." },
      { step: 6, key: "type_investisseur", label: "Type d'investisseur ciblé",    type: "textarea", placeholder: "Business angel, VC, impact investor, fonds régionaux..." },
      { step: 6, key: "objectif_18m",      label: "Objectif à 18 mois post-levée",type: "textarea", required: true },
    ],
  },

  {
    id: "marketing",
    category: "business",
    title: "Plan Marketing",
    description: "Stratégie marketing complète avec plan d'action détaillé.",
    priceFcfa: 14925,
    icon: "Megaphone",
    steps: [
      { number: 1, title: "Entreprise & Offre" },
      { number: 2, title: "Analyse de marché" },
      { number: 3, title: "Cibles & Personas" },
      { number: 4, title: "Stratégie & Mix marketing" },
      { number: 5, title: "Budget & KPIs" },
    ],
    fields: [
      { step: 1, key: "entreprise",        label: "Nom de l'entreprise",          type: "text",     required: true },
      { step: 1, key: "secteur",           label: "Secteur d'activité",           type: "text",     required: true },
      { step: 1, key: "produit",           label: "Produit / Service à promouvoir",type: "textarea", required: true, placeholder: "Décrivez votre offre, ses caractéristiques, son prix actuel..." },
      { step: 1, key: "usp",               label: "Proposition de valeur unique (USP)", type: "textarea", required: true },
      { step: 1, key: "zone_geo",          label: "Zone géographique ciblée",     type: "text",     required: true },
      { step: 2, key: "concurrents",       label: "Concurrents directs & indirects", type: "textarea", required: true },
      { step: 2, key: "tendances_marche",  label: "Tendances du marché",          type: "textarea", placeholder: "Tendances actuelles qui influencent votre secteur..." },
      { step: 2, key: "analyse_swot",      label: "Analyse SWOT marketing",       type: "textarea", placeholder: "Forces, faiblesses, opportunités, menaces marketing..." },
      { step: 3, key: "cible_principale",  label: "Cible principale",             type: "textarea", required: true, placeholder: "Âge, genre, revenu, localisation, comportements, douleurs..." },
      { step: 3, key: "cible_secondaire",  label: "Cible secondaire (si applicable)", type: "textarea" },
      { step: 3, key: "parcours_achat",    label: "Parcours d'achat du client",   type: "textarea", placeholder: "Comment votre client découvre, évalue et achète votre offre ?" },
      { step: 4, key: "positionnement",    label: "Positionnement souhaité",      type: "textarea", required: true, placeholder: "Comment voulez-vous être perçu vs la concurrence ?" },
      { step: 4, key: "canaux_marketing",  label: "Canaux marketing à utiliser",  type: "textarea", required: true, placeholder: "Réseaux sociaux, SEO, events, partenariats, pub payante, WhatsApp..." },
      { step: 4, key: "messages_cles",     label: "Messages clés à véhiculer",    type: "textarea", required: true },
      { step: 4, key: "actions_prioritaires",label: "Top 5 actions prioritaires", type: "textarea", required: true, placeholder: "Actions concrètes avec délai et responsable..." },
      { step: 5, key: "budget",            label: "Budget marketing mensuel (FCFA)", type: "text",  required: true },
      { step: 5, key: "repartition_budget",label: "Répartition du budget",        type: "textarea", placeholder: "40% digital, 30% events, 30% print..." },
      { step: 5, key: "kpis",              label: "KPIs à suivre",                type: "textarea", required: true, placeholder: "Taux de conversion, CAC, ROAS, taux d'engagement..." },
      { step: 5, key: "objectifs_chiffres",label: "Objectifs chiffrés à 6 mois",  type: "textarea", required: true, placeholder: "X nouveaux clients, Y FCFA de CA, Z% de notoriété..." },
    ],
  },

  {
    id: "finances",
    category: "business",
    title: "Prévisions Financières",
    description: "Tableau financier sur 3 ans avec compte de résultat et seuil de rentabilité.",
    priceFcfa: 18675,
    icon: "Calculator",
    steps: [
      { number: 1, title: "Entreprise & Activité" },
      { number: 2, title: "Revenus & Ventes" },
      { number: 3, title: "Charges & Coûts" },
      { number: 4, title: "Investissements & Financement" },
      { number: 5, title: "Hypothèses & Contexte" },
    ],
    fields: [
      { step: 1, key: "entreprise",        label: "Nom de l'entreprise",          type: "text",     required: true },
      { step: 1, key: "secteur",           label: "Secteur / Activité",           type: "text",     required: true },
      { step: 1, key: "pays",              label: "Pays",                         type: "text",     required: true },
      { step: 1, key: "stade",             label: "Stade de l'entreprise",        type: "select",   options: ["Création", "Démarrage (<1 an)", "Croissance (1-3 ans)", "Maturité (>3 ans)"] },
      { step: 1, key: "monnaie",           label: "Monnaie de référence",         type: "select",   options: ["FCFA (XOF)", "FCFA (XAF)", "EUR", "USD", "GHS", "NGN"] },
      { step: 2, key: "produits_lignes",   label: "Lignes de produits / services",type: "textarea", required: true, placeholder: "Produit A: prix X, volume prévu Y par mois; Produit B:..." },
      { step: 2, key: "ca_an1",            label: "CA prévisionnel An 1",         type: "text",     required: true },
      { step: 2, key: "ca_an2",            label: "CA prévisionnel An 2",         type: "text",     required: true },
      { step: 2, key: "ca_an3",            label: "CA prévisionnel An 3",         type: "text",     required: true },
      { step: 2, key: "croissance",        label: "Hypothèse de croissance annuelle", type: "text", placeholder: "Ex: +30% An 2, +20% An 3" },
      { step: 3, key: "salaires",          label: "Masse salariale mensuelle",    type: "text",     required: true },
      { step: 3, key: "loyer",             label: "Loyer mensuel",                type: "text" },
      { step: 3, key: "charges_fixes",     label: "Autres charges fixes mensuelles", type: "textarea", required: true, placeholder: "Électricité, internet, abonnements, assurances..." },
      { step: 3, key: "cout_variable",     label: "Coût variable (% du CA ou montant/unité)", type: "textarea", required: true, placeholder: "Matières premières, commissions, transport..." },
      { step: 3, key: "autres_charges",    label: "Autres charges importantes",   type: "textarea", placeholder: "Charges exceptionnelles, provisions..." },
      { step: 4, key: "investissement_total",label: "Investissement initial total",type: "text",   required: true },
      { step: 4, key: "detail_investissement",label: "Détail des investissements",type: "textarea", required: true, placeholder: "Matériel X FCFA, Aménagement Y FCFA, Stock initial Z FCFA..." },
      { step: 4, key: "financement_sources",label: "Sources de financement",      type: "textarea", required: true, placeholder: "Apport propre: X FCFA, Crédit: Y FCFA, Subvention: Z FCFA..." },
      { step: 4, key: "credit_conditions", label: "Conditions du crédit (si applicable)", type: "text", placeholder: "Montant, taux, durée, remboursement mensuel" },
      { step: 5, key: "taux_imposition",   label: "Taux d'imposition applicable", type: "text",     placeholder: "Ex: IS 27.5% au Togo, BIC 30% en Côte d'Ivoire..." },
      { step: 5, key: "autres_hypotheses", label: "Autres hypothèses importantes",type: "textarea", placeholder: "Taux de change, inflation, saisonnalité..." },
      { step: 5, key: "seuil_rentabilite", label: "Objectif de seuil de rentabilité", type: "text", placeholder: "À quel mois souhaitez-vous être rentable ?" },
    ],
  },

  {
    id: "pack_business",
    category: "business",
    title: "Pack Business Complet",
    description: "Business Plan + BMC + Plan Marketing.",
    priceFcfa: 44925,
    badge: "Pack",
    icon: "Briefcase",
    steps: [
      { number: 1, title: "Projet & Contexte" },
      { number: 2, title: "Marché & Concurrence" },
      { number: 3, title: "Stratégie commerciale" },
      { number: 4, title: "Plan financier" },
      { number: 5, title: "Organisation & Risques" },
      { number: 6, title: "Marketing & Communication" },
      { number: 7, title: "Canvas & Modèle économique" },
      { number: 8, title: "Annexes & Compléments" },
    ],
    fields: [
      { step: 1, key: "nom_projet",        label: "Nom du projet / entreprise",   type: "text",     required: true },
      { step: 1, key: "forme_juridique",   label: "Forme juridique",              type: "select",   options: ["SARL", "SA", "SAS", "GIE", "Auto-entrepreneur"], required: true },
      { step: 1, key: "secteur",           label: "Secteur d'activité",           type: "text",     required: true },
      { step: 1, key: "description",       label: "Description complète du projet",type: "textarea", required: true },
      { step: 1, key: "vision_mission",    label: "Vision & Mission",             type: "textarea" },
      { step: 2, key: "marche_cible",      label: "Marché cible",                 type: "textarea", required: true },
      { step: 2, key: "taille_marche",     label: "Taille du marché",             type: "text" },
      { step: 2, key: "concurrents",       label: "Concurrents principaux",       type: "textarea", required: true },
      { step: 2, key: "avantage",          label: "Avantage concurrentiel",       type: "textarea", required: true },
      { step: 3, key: "offre",             label: "Offre détaillée (produits/services)", type: "textarea", required: true },
      { step: 3, key: "prix",              label: "Structure de prix",            type: "textarea", required: true },
      { step: 3, key: "canaux",            label: "Canaux de vente",              type: "textarea", required: true },
      { step: 4, key: "investissement",    label: "Investissement initial",       type: "text",     required: true },
      { step: 4, key: "ca_previsionnel",   label: "CA An 1 / An 2 / An 3",       type: "textarea", required: true },
      { step: 4, key: "charges",           label: "Charges principales",          type: "textarea", required: true },
      { step: 4, key: "financement",       label: "Sources de financement",       type: "textarea", required: true },
      { step: 5, key: "equipe",            label: "Équipe fondatrice",            type: "textarea", required: true },
      { step: 5, key: "effectif_prevu",    label: "Effectif prévu à 3 ans",       type: "text" },
      { step: 5, key: "risques",           label: "Risques & mitigation",         type: "textarea", required: true },
      { step: 6, key: "cible_marketing",   label: "Cible marketing",              type: "textarea", required: true },
      { step: 6, key: "canaux_marketing",  label: "Canaux marketing",             type: "textarea", required: true },
      { step: 6, key: "budget_marketing",  label: "Budget marketing mensuel",     type: "text" },
      { step: 7, key: "proposition_valeur",label: "Proposition de valeur (BMC)", type: "textarea", required: true },
      { step: 7, key: "segments",          label: "Segments clients (BMC)",       type: "textarea", required: true },
      { step: 7, key: "sources_revenus",   label: "Sources de revenus",           type: "textarea", required: true },
      { step: 7, key: "structure_couts",   label: "Structure de coûts",           type: "textarea", required: true },
      { step: 8, key: "pays",              label: "Pays / Zone",                  type: "text",     required: true },
      { step: 8, key: "impact_social",     label: "Impact social",                type: "textarea" },
      { step: 8, key: "infos_complementaires", label: "Informations complémentaires", type: "textarea" },
    ],
  },

  // ─── ARCHITECTURE ──────────────────────────────────────────────────────────
  {
    id: "archi",
    category: "architecture",
    title: "Programme Architectural",
    description: "Programme pièce par pièce avec surfaces, matériaux et estimation en FCFA.",
    priceFcfa: 26175,
    badge: "Exclusif",
    icon: "Home",
    steps: [
      { number: 1, title: "Maître d'ouvrage & Projet" },
      { number: 2, title: "Programme des espaces" },
      { number: 3, title: "Matériaux & Finitions" },
      { number: 4, title: "Équipements techniques" },
      { number: 5, title: "Budget & Contraintes" },
      { number: 6, title: "Contexte & Réglementaire" },
    ],
    fields: [
      { step: 1, key: "nom_maitre_ouvrage",label: "Nom du maître d'ouvrage",      type: "text",     required: true },
      { step: 1, key: "contact",           label: "Contact (email / tél)",        type: "text" },
      { step: 1, key: "type_construction", label: "Type de construction",         type: "select",   options: ["Villa individuelle", "Immeuble résidentiel", "Bâtiment commercial", "Bureau", "Hôtel", "École", "Clinique", "Entrepôt", "Mixte"], required: true },
      { step: 1, key: "localisation",      label: "Localisation du terrain",      type: "text",     required: true },
      { step: 1, key: "surface_terrain",   label: "Surface du terrain (m²)",      type: "text",     required: true },
      { step: 1, key: "surface_batiment",  label: "Surface bâtie souhaitée (m²)", type: "text",     required: true },
      { step: 1, key: "nb_niveaux",        label: "Nombre de niveaux",            type: "select",   options: ["Rez-de-chaussée", "R+1", "R+2", "R+3", "R+4 et plus"] },
      { step: 2, key: "nb_chambres",       label: "Nombre de chambres",           type: "text",     required: true },
      { step: 2, key: "nb_salles_bain",    label: "Nombre de salles de bain",     type: "text" },
      { step: 2, key: "salon_sejour",      label: "Salon / Séjour (superficie)",  type: "text" },
      { step: 2, key: "cuisine",           label: "Type de cuisine",              type: "select",   options: ["Ouverte", "Fermée", "Américaine", "Extérieure"] },
      { step: 2, key: "espaces_speciaux",  label: "Espaces spéciaux",             type: "textarea", placeholder: "Bureau à domicile, salle de sport, cinéma, bibliothèque, gardiennage..." },
      { step: 2, key: "exterieur",         label: "Espaces extérieurs",           type: "textarea", placeholder: "Piscine, jardin, parking, terrasse, pergola..." },
      { step: 3, key: "style_architectural",label: "Style architectural souhaité",type: "select",   options: ["Contemporain", "Tropical moderne", "Classique", "Méditerranéen", "Minimaliste", "Traditionnel africain"] },
      { step: 3, key: "materiaux_gros_oeuvre",label: "Matériaux gros œuvre",     type: "textarea", placeholder: "Structure béton armé, parpaings, brique, acier..." },
      { step: 3, key: "finitions_sols",    label: "Finitions sols",               type: "textarea", placeholder: "Carrelage (type/dimension), marbre, parquet, béton poli..." },
      { step: 3, key: "finitions_murs",    label: "Finitions murs & façade",      type: "textarea", placeholder: "Peinture, enduit, crépi, pierre, verre, zinc..." },
      { step: 3, key: "menuiseries",       label: "Menuiseries (portes/fenêtres)", type: "select",  options: ["Aluminium", "PVC", "Bois", "Acier", "Mixte"] },
      { step: 4, key: "electricite",       label: "Installation électrique",      type: "textarea", placeholder: "Nombre de circuits, domotique, groupe électrogène, panneaux solaires..." },
      { step: 4, key: "plomberie",         label: "Plomberie & Sanitaires",       type: "textarea", placeholder: "Château d'eau, fosse septique, réseau d'eau chaude, chauffe-eau..." },
      { step: 4, key: "climatisation",     label: "Climatisation & Ventilation",  type: "select",   options: ["Split système", "Climatisation centralisée", "VMC", "Ventilation naturelle", "Non prévue"] },
      { step: 4, key: "securite",          label: "Systèmes de sécurité",         type: "textarea", placeholder: "Alarme, caméras, interphone, portail automatique..." },
      { step: 5, key: "budget_total",      label: "Budget total en FCFA",         type: "text",     required: true },
      { step: 5, key: "contraintes_budget",label: "Contraintes budgétaires",      type: "textarea", placeholder: "Postes non négociables, postes où économiser..." },
      { step: 5, key: "delai_construction",label: "Délai de construction souhaité",type: "text",    placeholder: "Ex: 18 mois" },
      { step: 5, key: "phasage",           label: "Phasage des travaux",          type: "select",   options: ["Réalisation complète", "Phase 1 puis phase 2", "Selon budget disponible"] },
      { step: 6, key: "pays",              label: "Pays",                         type: "text",     required: true },
      { step: 6, key: "urbanisme",         label: "Règles d'urbanisme connues",   type: "textarea", placeholder: "COS, CES, hauteur maximale, retrait imposé..." },
      { step: 6, key: "besoins_speciaux",  label: "Besoins spéciaux / PMR",       type: "textarea", placeholder: "Accessibilité PMR, normes parasismiques, inondations..." },
    ],
  },

  {
    id: "devis",
    category: "architecture",
    title: "Devis de Construction",
    description: "Devis détaillé par lot de travaux avec prix unitaires.",
    priceFcfa: 14925,
    icon: "ClipboardList",
    steps: [
      { number: 1, title: "Maître d'ouvrage & Projet" },
      { number: 2, title: "Description des travaux" },
      { number: 3, title: "Lots de travaux" },
      { number: 4, title: "Matériaux & Main d'œuvre" },
      { number: 5, title: "Délais & Conditions" },
    ],
    fields: [
      { step: 1, key: "nom_client",        label: "Nom du client",                type: "text",     required: true },
      { step: 1, key: "localisation",      label: "Localisation du chantier",     type: "text",     required: true },
      { step: 1, key: "type_travaux",      label: "Type de travaux",              type: "select",   options: ["Construction neuve", "Rénovation", "Extension", "Aménagement intérieur", "Travaux extérieurs"], required: true },
      { step: 1, key: "surface",           label: "Surface concernée (m²)",       type: "text",     required: true },
      { step: 2, key: "description_projet",label: "Description complète du projet", type: "textarea", required: true },
      { step: 2, key: "standing",          label: "Standing souhaité",            type: "select",   options: ["Économique", "Standard", "Haut standing", "Luxe"], required: true },
      { step: 2, key: "etat_existant",     label: "État actuel (rénovation)",     type: "textarea", placeholder: "Décrivez l'état actuel si c'est une rénovation..." },
      { step: 3, key: "lot_gros_oeuvre",   label: "Lot 1 — Gros œuvre",           type: "textarea", placeholder: "Fondations, dalle, murs, charpente, toiture... détaillez" },
      { step: 3, key: "lot_second_oeuvre", label: "Lot 2 — Second œuvre",         type: "textarea", placeholder: "Cloisonnement, isolation, plâtrerie, carrelage, peinture..." },
      { step: 3, key: "lot_elec",          label: "Lot 3 — Électricité",          type: "textarea", placeholder: "Tableau, câblage, prises, luminaires, groupe électrogène..." },
      { step: 3, key: "lot_plomberie",     label: "Lot 4 — Plomberie & Sanitaires",type: "textarea", placeholder: "Réseau eau, sanitaires, fosse, château d'eau..." },
      { step: 3, key: "lot_menuiserie",    label: "Lot 5 — Menuiserie",           type: "textarea", placeholder: "Portes, fenêtres, placards, escaliers..." },
      { step: 3, key: "lot_autres",        label: "Autres lots",                  type: "textarea", placeholder: "Climatisation, piscine, aménagement extérieur, sécurité..." },
      { step: 4, key: "materiaux_pref",    label: "Préférences matériaux",        type: "textarea", placeholder: "Marques, fournisseurs, qualités souhaités..." },
      { step: 4, key: "main_oeuvre",       label: "Main d'œuvre disponible",      type: "select",   options: ["À inclure dans le devis", "Non incluse (fourniture seule)", "À discuter"] },
      { step: 5, key: "delai",             label: "Délai souhaité pour les travaux",type: "text",   required: true },
      { step: 5, key: "budget_cible",      label: "Budget cible (FCFA)",          type: "text",     required: true },
      { step: 5, key: "conditions_paiement",label: "Conditions de paiement souhaitées",type: "select",options: ["Avance + solde", "Paiement par phases", "Paiement à réception", "À négocier"] },
    ],
  },

  {
    id: "cdc",
    category: "architecture",
    title: "Cahier des Charges",
    description: "CDC technique complet pour lancer un appel d'offres de construction.",
    priceFcfa: 18675,
    icon: "FileCheck",
    steps: [
      { number: 1, title: "Commanditaire & Contexte" },
      { number: 2, title: "Description du projet" },
      { number: 3, title: "Exigences techniques" },
      { number: 4, title: "Lots & Prestations" },
      { number: 5, title: "Planning & Contractuel" },
      { number: 6, title: "Critères & Sélection" },
    ],
    fields: [
      { step: 1, key: "commanditaire",     label: "Commanditaire / Maître d'ouvrage",type: "text",  required: true },
      { step: 1, key: "contact",           label: "Contact",                      type: "text" },
      { step: 1, key: "contexte",          label: "Contexte du projet",           type: "textarea", required: true },
      { step: 1, key: "objectifs",         label: "Objectifs du CDC",             type: "textarea", required: true },
      { step: 2, key: "type_projet",       label: "Type de projet",               type: "text",     required: true },
      { step: 2, key: "localisation",      label: "Localisation",                 type: "text",     required: true },
      { step: 2, key: "surface_shon",      label: "Surface SHON / SHOB (m²)",     type: "text",     required: true },
      { step: 2, key: "programme",         label: "Programme détaillé",           type: "textarea", required: true, placeholder: "Espaces, fonctions, surfaces par local..." },
      { step: 3, key: "normes_applicables",label: "Normes applicables",           type: "textarea", placeholder: "Normes OHADA, ISO, locales, sismiques, incendie..." },
      { step: 3, key: "exig_techniques",   label: "Exigences techniques",         type: "textarea", required: true, placeholder: "Structure, matériaux, performances thermiques, acoustique..." },
      { step: 3, key: "exig_environnement",label: "Exigences environnementales",  type: "textarea", placeholder: "HQE, matériaux locaux, énergie solaire, gestion des eaux..." },
      { step: 4, key: "lots_travaux",      label: "Décomposition en lots",        type: "textarea", required: true, placeholder: "Lot 1: Gros œuvre, Lot 2: Électricité, Lot 3: Plomberie..." },
      { step: 4, key: "prestations_exclues",label: "Prestations exclues du CDC",  type: "textarea" },
      { step: 5, key: "planning_global",   label: "Planning global souhaité",     type: "textarea", required: true, placeholder: "Date de lancement AO, date remise offres, date démarrage, fin travaux" },
      { step: 5, key: "budget_enveloppe",  label: "Enveloppe budgétaire (FCFA)", type: "text" },
      { step: 5, key: "modalites_paiement",label: "Modalités de paiement",        type: "textarea", placeholder: "Avance, situation mensuelle, retenue de garantie..." },
      { step: 6, key: "criteres_selection",label: "Critères de sélection des offres",type: "textarea",required: true, placeholder: "% technique, % financier, références exigées, agréments..." },
      { step: 6, key: "docs_a_fournir",    label: "Documents à fournir par les soumissionnaires", type: "textarea", required: true },
    ],
  },

  {
    id: "permis",
    category: "architecture",
    title: "Dossier Permis de Construire",
    description: "Dossier complet pour demande de permis de construire.",
    priceFcfa: 22425,
    icon: "Stamp",
    steps: [
      { number: 1, title: "Demandeur" },
      { number: 2, title: "Terrain & Parcelle" },
      { number: 3, title: "Nature des travaux" },
      { number: 4, title: "Surfaces & Dimensions" },
      { number: 5, title: "Conformité réglementaire" },
    ],
    fields: [
      { step: 1, key: "nom_demandeur",     label: "Nom complet du demandeur",     type: "text",     required: true },
      { step: 1, key: "qualite",           label: "Qualité du demandeur",         type: "select",   options: ["Propriétaire", "Locataire avec autorisation", "Promoteur", "Maître d'ouvrage délégué"] },
      { step: 1, key: "adresse_demandeur", label: "Adresse du demandeur",         type: "text",     required: true },
      { step: 1, key: "contact",           label: "Téléphone / Email",            type: "text",     required: true },
      { step: 2, key: "localisation",      label: "Adresse / Localisation du terrain", type: "text", required: true },
      { step: 2, key: "section_cadastrale",label: "Section cadastrale / N° de lot",type: "text" },
      { step: 2, key: "surface_terrain",   label: "Surface du terrain (m²)",      type: "text",     required: true },
      { step: 2, key: "zone_urbanisme",    label: "Zone d'urbanisme",             type: "text",     placeholder: "Zone résidentielle, commerciale, mixte..." },
      { step: 2, key: "acces_viabilites",  label: "Accès & Viabilités",           type: "textarea", placeholder: "Eau, électricité, voirie, assainissement..." },
      { step: 3, key: "nature_travaux",    label: "Nature des travaux",           type: "select",   options: ["Construction neuve", "Extension", "Surélévation", "Réhabilitation", "Changement de destination"], required: true },
      { step: 3, key: "destination",       label: "Destination du bâtiment",      type: "select",   options: ["Habitation", "Commerce", "Bureau", "Industrie", "Hôtel", "Enseignement", "Santé", "Mixte"] },
      { step: 3, key: "description_projet",label: "Description du projet",        type: "textarea", required: true },
      { step: 4, key: "shon",              label: "SHON — Surface Hors Œuvre Nette (m²)", type: "text", required: true },
      { step: 4, key: "shob",              label: "SHOB — Surface Hors Œuvre Brute (m²)", type: "text" },
      { step: 4, key: "emprise_sol",       label: "Emprise au sol (m²)",          type: "text",     required: true },
      { step: 4, key: "hauteur_totale",    label: "Hauteur totale (m)",           type: "text",     required: true },
      { step: 4, key: "nb_niveaux",        label: "Nombre de niveaux",            type: "text",     required: true },
      { step: 5, key: "pays",              label: "Pays",                         type: "text",     required: true },
      { step: 5, key: "cos_ces",           label: "COS / CES applicable",         type: "text",     placeholder: "Coefficient d'occupation des sols..." },
      { step: 5, key: "retraits",          label: "Retraits réglementaires",      type: "textarea", placeholder: "Retrait façade, latéraux, fond de parcelle..." },
      { step: 5, key: "architecte",        label: "Nom de l'architecte / bureau",type: "text" },
      { step: 5, key: "observations",      label: "Observations / Documents disponibles", type: "textarea", placeholder: "Plan de masse disponible, étude de sol, acte de propriété..." },
    ],
  },

  {
    id: "pack_archi",
    category: "architecture",
    title: "Pack Architecture Complet",
    description: "Programme + Devis + Cahier des charges en un seul pack.",
    priceFcfa: 52425,
    badge: "Pack",
    icon: "Building",
    steps: [
      { number: 1, title: "Maître d'ouvrage & Terrain" },
      { number: 2, title: "Programme architectural" },
      { number: 3, title: "Matériaux & Standing" },
      { number: 4, title: "Lots de travaux & Devis" },
      { number: 5, title: "Budget & Délais" },
      { number: 6, title: "CDC & Critères de sélection" },
      { number: 7, title: "Réglementation & Contexte" },
      { number: 8, title: "Compléments" },
    ],
    fields: [
      { step: 1, key: "nom_maitre",        label: "Maître d'ouvrage",             type: "text",     required: true },
      { step: 1, key: "localisation",      label: "Localisation du projet",       type: "text",     required: true },
      { step: 1, key: "surface_terrain",   label: "Surface terrain (m²)",         type: "text",     required: true },
      { step: 1, key: "type_construction", label: "Type de construction",         type: "select",   options: ["Villa", "Immeuble", "Commercial", "Bureau", "Hôtel", "École", "Clinique"], required: true },
      { step: 2, key: "surface_batiment",  label: "Surface bâtie (m²)",           type: "text",     required: true },
      { step: 2, key: "nb_niveaux",        label: "Nombre de niveaux",            type: "text" },
      { step: 2, key: "programme_espaces", label: "Programme des espaces",        type: "textarea", required: true, placeholder: "Nombre pièces, surfaces, espaces spéciaux..." },
      { step: 3, key: "standing",          label: "Standing souhaité",            type: "select",   options: ["Économique", "Standard", "Haut standing", "Luxe"], required: true },
      { step: 3, key: "style",             label: "Style architectural",          type: "select",   options: ["Contemporain", "Tropical moderne", "Classique", "Minimaliste"] },
      { step: 3, key: "materiaux",         label: "Matériaux & finitions",        type: "textarea", required: true },
      { step: 4, key: "lots_details",      label: "Détail des lots de travaux",   type: "textarea", required: true, placeholder: "Gros œuvre, second œuvre, électricité, plomberie, menuiserie..." },
      { step: 4, key: "equipements_tech",  label: "Équipements techniques",       type: "textarea", placeholder: "Clim, solaire, sécurité, domotique..." },
      { step: 5, key: "budget_total",      label: "Budget total (FCFA)",          type: "text",     required: true },
      { step: 5, key: "delai",             label: "Délai de réalisation",         type: "text",     required: true },
      { step: 5, key: "phasage",           label: "Phasage prévu",                type: "textarea" },
      { step: 6, key: "normes",            label: "Normes & exigences techniques", type: "textarea", placeholder: "Normes OHADA, sismiques, incendie, environnementales..." },
      { step: 6, key: "criteres_selection",label: "Critères de sélection entrepreneurs", type: "textarea", required: true },
      { step: 7, key: "pays",              label: "Pays",                         type: "text",     required: true },
      { step: 7, key: "reglementation",    label: "Contraintes réglementaires",   type: "textarea" },
      { step: 8, key: "infos_complementaires", label: "Informations complémentaires", type: "textarea" },
    ],
  },

  // ─── JURIDIQUE ─────────────────────────────────────────────────────────────
  {
    id: "statuts",
    category: "juridique",
    title: "Statuts de Société",
    description: "Statuts officiels conformes au droit OHADA.",
    priceFcfa: 14925,
    badge: "Exclusif",
    icon: "Scale",
    steps: [
      { number: 1, title: "Identification de la société" },
      { number: 2, title: "Forme juridique & Capital" },
      { number: 3, title: "Objet social & Activités" },
      { number: 4, title: "Associés & Gérants" },
      { number: 5, title: "Gouvernance" },
      { number: 6, title: "Dispositions spéciales" },
    ],
    fields: [
      { step: 1, key: "nom_societe",       label: "Dénomination sociale",         type: "text",     required: true },
      { step: 1, key: "sigle",             label: "Sigle (si applicable)",        type: "text" },
      { step: 1, key: "siege",             label: "Siège social (adresse complète)",type: "text",   required: true },
      { step: 1, key: "pays",              label: "Pays",                         type: "text",     required: true, placeholder: "Togo, Côte d'Ivoire, Sénégal, Cameroun..." },
      { step: 1, key: "ville",             label: "Ville",                        type: "text",     required: true },
      { step: 2, key: "forme_juridique",   label: "Forme juridique",              type: "select",   options: ["SARL", "SA", "SAS", "SASU", "SNC", "SCS", "GIE", "SP"], required: true },
      { step: 2, key: "capital_social",    label: "Capital social (FCFA)",        type: "text",     required: true },
      { step: 2, key: "nature_apports",    label: "Nature des apports",           type: "select",   options: ["Numéraire uniquement", "Numéraire + Nature", "Nature uniquement"] },
      { step: 2, key: "parts_actions",     label: "Nombre de parts / actions",    type: "text",     required: true },
      { step: 2, key: "valeur_nominale",   label: "Valeur nominale par part/action",type: "text",  required: true },
      { step: 3, key: "objet_social",      label: "Objet social principal",       type: "textarea", required: true, placeholder: "Activités principales exercées par la société..." },
      { step: 3, key: "activites_secondaires",label: "Activités accessoires / secondaires",type: "textarea" },
      { step: 3, key: "duree_societe",     label: "Durée de la société (années)", type: "text",     placeholder: "99 ans en général" },
      { step: 4, key: "associes",          label: "Liste des associés",           type: "textarea", required: true, placeholder: "Pour chaque associé: Nom, nationalité, adresse, nbre de parts, % capital" },
      { step: 4, key: "gerant_principal",  label: "Gérant / PDG principal",       type: "text",     required: true, placeholder: "Nom complet, nationalité, adresse" },
      { step: 4, key: "autres_dirigeants", label: "Autres dirigeants (si applicable)",type: "textarea", placeholder: "Co-gérant, DG, administrateurs..." },
      { step: 5, key: "regime_decisions",  label: "Régime des décisions collectives",type: "textarea",required: true, placeholder: "Quorum, majorité requise pour les AG ordinaires et extraordinaires..." },
      { step: 5, key: "cession_parts",     label: "Conditions de cession des parts",type: "textarea", placeholder: "Droit de préemption, agrément des associés..." },
      { step: 5, key: "exercice_social",   label: "Date de clôture de l'exercice social",type: "text", placeholder: "Ex: 31 décembre" },
      { step: 6, key: "clause_non_concurrence",label: "Clause de non-concurrence",type: "select",  options: ["Oui, à préciser", "Non"], },
      { step: 6, key: "clause_arbitrage",  label: "Clause d'arbitrage OHADA",     type: "select",   options: ["Oui (CCJA)", "Oui (arbitrage ad hoc)", "Non"] },
      { step: 6, key: "dispositions_speciales",label: "Dispositions particulières souhaitées",type: "textarea", placeholder: "Clause de préférence, pacte d'associés à intégrer..." },
    ],
  },

  {
    id: "contrat",
    category: "juridique",
    title: "Contrat Professionnel",
    description: "Contrat sur mesure : prestation, partenariat, confidentialité, etc.",
    priceFcfa: 11175,
    icon: "Handshake",
    steps: [
      { number: 1, title: "Identification des parties" },
      { number: 2, title: "Objet & Durée" },
      { number: 3, title: "Obligations des parties" },
      { number: 4, title: "Rémunération & Paiement" },
      { number: 5, title: "Clauses spéciales & Droit applicable" },
    ],
    fields: [
      { step: 1, key: "type_contrat",      label: "Type de contrat",              type: "select",   options: ["Contrat de prestation de services", "Contrat de partenariat", "NDA / Confidentialité", "Contrat de travail", "Contrat commercial", "Contrat de bail", "Contrat de cession de droits", "Autre"], required: true },
      { step: 1, key: "partie1_nom",       label: "Partie 1 — Nom / Raison sociale", type: "text", required: true },
      { step: 1, key: "partie1_qualite",   label: "Partie 1 — Qualité / Rôle",    type: "text",     required: true, placeholder: "Prestataire, Partenaire, Employeur..." },
      { step: 1, key: "partie1_adresse",   label: "Partie 1 — Adresse",           type: "text" },
      { step: 1, key: "partie2_nom",       label: "Partie 2 — Nom / Raison sociale", type: "text", required: true },
      { step: 1, key: "partie2_qualite",   label: "Partie 2 — Qualité / Rôle",    type: "text",     required: true },
      { step: 1, key: "partie2_adresse",   label: "Partie 2 — Adresse",           type: "text" },
      { step: 2, key: "objet",             label: "Objet du contrat",             type: "textarea", required: true, placeholder: "Décrivez précisément la prestation, le partenariat, l'accord..." },
      { step: 2, key: "date_debut",        label: "Date de début",                type: "text",     required: true },
      { step: 2, key: "duree",             label: "Durée / Date de fin",          type: "text",     required: true, placeholder: "12 mois, ou jusqu'au 31/12/2026" },
      { step: 2, key: "renouvellement",    label: "Renouvellement",               type: "select",   options: ["Tacite reconduction", "À négocier", "Pas de renouvellement"] },
      { step: 3, key: "obligations_partie1",label: "Obligations de la Partie 1",  type: "textarea", required: true },
      { step: 3, key: "obligations_partie2",label: "Obligations de la Partie 2",  type: "textarea", required: true },
      { step: 3, key: "livrables",         label: "Livrables / Résultats attendus",type: "textarea", placeholder: "Décrire les livrables, délais de livraison, critères d'acceptation..." },
      { step: 4, key: "montant",           label: "Montant / Rémunération",       type: "text",     required: true, placeholder: "Montant total, tarif horaire, ou mensuel en FCFA" },
      { step: 4, key: "modalites_paiement",label: "Modalités de paiement",        type: "textarea", required: true, placeholder: "Acompte X%, solde à réception, paiement mensuel..." },
      { step: 4, key: "penalites",         label: "Pénalités de retard",          type: "text",     placeholder: "Ex: 1% par semaine de retard" },
      { step: 5, key: "confidentialite",   label: "Clause de confidentialité",    type: "select",   options: ["Inclure (standard)", "Inclure (renforcée)", "Non applicable"] },
      { step: 5, key: "non_concurrence",   label: "Clause de non-concurrence",    type: "select",   options: ["Oui (6 mois)", "Oui (12 mois)", "Oui (24 mois)", "Non"] },
      { step: 5, key: "propriete_intellectuelle",label: "Propriété intellectuelle",type: "select",   options: ["Appartient au client", "Appartient au prestataire", "Partagée", "Non applicable"] },
      { step: 5, key: "resiliation",       label: "Conditions de résiliation",    type: "textarea", required: true, placeholder: "Délai de préavis, motifs, conséquences..." },
      { step: 5, key: "droit_applicable",  label: "Droit applicable & juridiction",type: "text",   required: true, placeholder: "Droit OHADA, droit togolais, tribunal compétent..." },
    ],
  },

  {
    id: "financement",
    category: "juridique",
    title: "Dossier de Financement",
    description: "Dossier complet pour demande de prêt ou financement bancaire.",
    priceFcfa: 18675,
    icon: "Banknote",
    steps: [
      { number: 1, title: "Entreprise & Porteur" },
      { number: 2, title: "Projet à financer" },
      { number: 3, title: "Plan financier" },
      { number: 4, title: "Garanties & Apports" },
      { number: 5, title: "Historique financier" },
      { number: 6, title: "Contexte & Compléments" },
    ],
    fields: [
      { step: 1, key: "nom_entreprise",    label: "Nom de l'entreprise",          type: "text",     required: true },
      { step: 1, key: "forme_juridique",   label: "Forme juridique",              type: "text",     required: true },
      { step: 1, key: "date_creation",     label: "Date de création",             type: "text" },
      { step: 1, key: "secteur",           label: "Secteur d'activité",           type: "text",     required: true },
      { step: 1, key: "dirigeant",         label: "Nom du dirigeant principal",   type: "text",     required: true },
      { step: 1, key: "adresse",           label: "Adresse du siège",             type: "text",     required: true },
      { step: 1, key: "effectif",          label: "Effectif actuel",              type: "text" },
      { step: 2, key: "objet_financement", label: "Objet du financement",         type: "textarea", required: true, placeholder: "À quoi servira le financement ? Équipements, stocks, BFR, extension..." },
      { step: 2, key: "montant_demande",   label: "Montant demandé (FCFA)",       type: "text",     required: true },
      { step: 2, key: "duree_credit",      label: "Durée souhaitée du crédit",    type: "text",     required: true, placeholder: "Ex: 36 mois, 5 ans" },
      { step: 2, key: "description_projet",label: "Description détaillée du projet",type: "textarea", required: true },
      { step: 2, key: "impact_prevu",      label: "Impact prévu (emplois, CA)",   type: "textarea", placeholder: "Emplois créés, augmentation CA, nouvelles capacités..." },
      { step: 3, key: "ca_annee_n",        label: "CA année N (actuel)",          type: "text" },
      { step: 3, key: "ca_annee_n1",       label: "CA An N+1 (prévisionnel)",     type: "text",     required: true },
      { step: 3, key: "ca_annee_n2",       label: "CA An N+2 (prévisionnel)",     type: "text" },
      { step: 3, key: "resultat_net",      label: "Résultat net actuel",          type: "text" },
      { step: 3, key: "remboursement_mensuel",label: "Capacité de remboursement mensuelle estimée",type: "text", required: true },
      { step: 4, key: "apport_personnel",  label: "Apport personnel (FCFA)",      type: "text",     required: true },
      { step: 4, key: "garanties",         label: "Garanties proposées",          type: "textarea", required: true, placeholder: "Hypothèque, nantissement, caution solidaire, assurance..." },
      { step: 4, key: "autres_financements",label: "Autres financements en cours",type: "textarea", placeholder: "Crédits existants, encours, leasing..." },
      { step: 5, key: "bilan_simplifie",   label: "Bilan simplifié (actif/passif)",type: "textarea", placeholder: "Actif total, dettes, capitaux propres... (si entreprise existante)" },
      { step: 5, key: "incidents_bancaires",label: "Incidents bancaires passés",  type: "select",   options: ["Aucun", "Résolus", "En cours de résolution"] },
      { step: 6, key: "banque_cible",      label: "Banque / Institution ciblée",  type: "text",     placeholder: "BTCI, Ecobank, BOA, microfinance..." },
      { step: 6, key: "pays",              label: "Pays",                         type: "text",     required: true },
      { step: 6, key: "infos_complementaires",label: "Informations complémentaires",type: "textarea" },
    ],
  },

  // ─── TRADUCTION ─────────────────────────────────────────────────────────────
  {
    id: "trad_s",
    category: "traduction",
    title: "Traduction Courte",
    description: "Traduction professionnelle jusqu'à 2 pages.",
    priceFcfa: 3675,
    badge: "Nouveau",
    icon: "Languages",
    steps: [
      { number: 1, title: "Paramètres de traduction" },
      { number: 2, title: "Texte & Instructions" },
    ],
    fields: [
      { step: 1, key: "langue_source",     label: "Langue source",                type: "select",   options: ["Français", "Anglais", "Espagnol", "Portugais", "Arabe", "Allemand"], required: true },
      { step: 1, key: "langue_cible",      label: "Langue cible",                 type: "select",   options: ["Français", "Anglais", "Espagnol", "Portugais", "Arabe", "Allemand"], required: true },
      { step: 1, key: "type_doc",          label: "Type de document",             type: "select",   options: ["Correspondance professionnelle", "Contrat", "CV", "Communiqué", "Article", "Notice", "Autre"] },
      { step: 1, key: "domaine",           label: "Domaine / Spécialité",         type: "select",   options: ["Juridique", "Business", "Technique", "Médical", "Académique", "Général"] },
      { step: 1, key: "ton",               label: "Ton souhaité",                 type: "select",   options: ["Formel", "Professionnel", "Neutre", "Informel"] },
      { step: 2, key: "texte",             label: "Texte à traduire (2 pages max)",type: "textarea", required: true, placeholder: "Collez votre texte ici..." },
      { step: 2, key: "terminologie",      label: "Terminologie spécifique à conserver", type: "textarea", placeholder: "Termes techniques, noms propres, acronymes à garder tels quels..." },
      { step: 2, key: "contexte",          label: "Contexte d'utilisation",       type: "textarea", placeholder: "À qui est destinée cette traduction ? Dans quel cadre sera-t-elle utilisée ?" },
    ],
  },

  {
    id: "trad_l",
    category: "traduction",
    title: "Traduction Longue",
    description: "Traduction professionnelle jusqu'à 10 pages.",
    priceFcfa: 11175,
    icon: "BookOpen",
    steps: [
      { number: 1, title: "Paramètres de traduction" },
      { number: 2, title: "Document & Contenu" },
      { number: 3, title: "Instructions spéciales" },
    ],
    fields: [
      { step: 1, key: "langue_source",     label: "Langue source",                type: "select",   options: ["Français", "Anglais", "Espagnol", "Portugais", "Arabe", "Allemand"], required: true },
      { step: 1, key: "langue_cible",      label: "Langue cible",                 type: "select",   options: ["Français", "Anglais", "Espagnol", "Portugais", "Arabe", "Allemand"], required: true },
      { step: 1, key: "type_doc",          label: "Type de document",             type: "select",   options: ["Rapport", "Business plan", "Contrat long", "Dossier juridique", "Manuel", "Rapport académique", "Autre"], required: true },
      { step: 1, key: "domaine",           label: "Domaine de spécialité",        type: "select",   options: ["Juridique", "Business/Finance", "Technique/Ingénierie", "Médical", "Académique", "ONG/Développement", "Général"] },
      { step: 2, key: "texte",             label: "Texte / Description du document (10p max)", type: "textarea", required: true, placeholder: "Collez le texte complet ou décrivez son contenu si trop long..." },
      { step: 2, key: "nb_pages",          label: "Nombre de pages estimé",       type: "text",     placeholder: "Ex: 7 pages" },
      { step: 2, key: "structure_doc",     label: "Structure du document",        type: "textarea", placeholder: "Sections, chapitres, parties principales..." },
      { step: 3, key: "terminologie",      label: "Terminologie spécifique",      type: "textarea", placeholder: "Termes techniques, sigles, noms propres à conserver..." },
      { step: 3, key: "ton",               label: "Ton & Registre",               type: "select",   options: ["Formel", "Académique", "Professionnel", "Neutre"] },
      { step: 3, key: "contexte_utilisation",label: "Contexte d'utilisation",     type: "textarea", required: true, placeholder: "Soumission bailleur, dépôt légal, usage interne, publication..." },
    ],
  },

  // ─── APPELS D'OFFRES ────────────────────────────────────────────────────────
  {
    id: "ao",
    category: "ao",
    title: "Réponse Appel d'Offres",
    description: "Offre technique et financière complète pour remporter des marchés.",
    priceFcfa: 29925,
    badge: "Premium",
    icon: "Trophy",
    steps: [
      { number: 1, title: "Entreprise soumissionnaire" },
      { number: 2, title: "Objet & Analyse de l'AO" },
      { number: 3, title: "Offre technique" },
      { number: 4, title: "Références & Expériences" },
      { number: 5, title: "Équipe mobilisée" },
      { number: 6, title: "Offre financière" },
      { number: 7, title: "Documents administratifs" },
    ],
    fields: [
      { step: 1, key: "nom_entreprise",    label: "Nom de l'entreprise",          type: "text",     required: true },
      { step: 1, key: "forme_juridique",   label: "Forme juridique",              type: "text",     required: true },
      { step: 1, key: "rc_rccm",           label: "N° RCCM / Registre commerce",  type: "text" },
      { step: 1, key: "siege",             label: "Siège social",                 type: "text",     required: true },
      { step: 1, key: "contact",           label: "Contact (email, tél, site)",   type: "textarea", required: true },
      { step: 1, key: "agrement",          label: "Agréments & Certifications",   type: "textarea", placeholder: "ISO, agréments sectoriels, certifications..." },
      { step: 2, key: "client_ao",         label: "Donneur d'ordre / Client",     type: "text",     required: true },
      { step: 2, key: "reference_ao",      label: "Référence de l'AO",            type: "text" },
      { step: 2, key: "objet_ao",          label: "Objet de l'appel d'offres",    type: "textarea", required: true },
      { step: 2, key: "montant_estime",    label: "Montant estimé du marché",     type: "text" },
      { step: 2, key: "criteres_evaluation",label: "Critères d'évaluation connus",type: "textarea", placeholder: "Technique: X%, Prix: Y%, Délai: Z%..." },
      { step: 3, key: "comprehension",     label: "Compréhension de la mission",  type: "textarea", required: true, placeholder: "Comment vous comprenez les besoins du client..." },
      { step: 3, key: "methodologie",      label: "Méthodologie proposée",        type: "textarea", required: true, placeholder: "Approche technique, phases, livrables, outils..." },
      { step: 3, key: "innovations",       label: "Éléments différenciants / Innovation",type: "textarea", placeholder: "Ce qui distingue votre offre des concurrents..." },
      { step: 3, key: "planning_technique",label: "Planning d'exécution",         type: "textarea", required: true, placeholder: "Phases, durées, jalons, délai global..." },
      { step: 4, key: "references_similaires",label: "Références similaires (3-5)",type: "textarea", required: true, placeholder: "Pour chaque référence: client, objet, montant, date, résultat..." },
      { step: 4, key: "certifications_qualite",label: "Certifications qualité",   type: "textarea" },
      { step: 5, key: "chef_projet",       label: "Chef de projet proposé",       type: "textarea", required: true, placeholder: "Nom, formation, expérience, rôle dans ce projet..." },
      { step: 5, key: "equipe_technique",  label: "Équipe technique",             type: "textarea", required: true, placeholder: "Membres, qualifications, rôles..." },
      { step: 5, key: "sous_traitants",    label: "Sous-traitants prévus",        type: "textarea", placeholder: "Nom, spécialité, part du marché..." },
      { step: 6, key: "montant_offre",     label: "Montant de votre offre (HT)",  type: "text",     required: true },
      { step: 6, key: "decomposition_prix",label: "Décomposition du prix",        type: "textarea", required: true, placeholder: "Main d'œuvre: X FCFA, Matériaux: Y FCFA, Frais généraux: Z FCFA..." },
      { step: 6, key: "modalites_paiement",label: "Modalités de paiement souhaitées",type: "select",options: ["Avance 30% + tranches", "Paiement mensuel", "Paiement à la livraison", "À négocier"] },
      { step: 7, key: "docs_admin",        label: "Documents administratifs disponibles",type: "textarea", required: true, placeholder: "RCCM, patente, attestations fiscales, assurances, etc..." },
      { step: 7, key: "validite_offre",    label: "Durée de validité de l'offre", type: "text",     placeholder: "Ex: 90 jours" },
    ],
  },

  {
    id: "ong",
    category: "ao",
    title: "Proposition de Projet ONG",
    description: "Proposition complète pour bailleur de fonds (UE, USAID, AFD…).",
    priceFcfa: 37425,
    badge: "Premium",
    icon: "Globe",
    steps: [
      { number: 1, title: "Organisation & Contexte" },
      { number: 2, title: "Problématique & Analyse" },
      { number: 3, title: "Objectifs & Résultats" },
      { number: 4, title: "Activités & Méthodologie" },
      { number: 5, title: "Bénéficiaires & Partenaires" },
      { number: 6, title: "Budget" },
      { number: 7, title: "Suivi & Évaluation" },
      { number: 8, title: "Durabilité & Annexes" },
    ],
    fields: [
      { step: 1, key: "nom_organisation",  label: "Nom de l'organisation",        type: "text",     required: true },
      { step: 1, key: "type_organisation", label: "Type",                         type: "select",   options: ["ONG locale", "ONG internationale", "Association", "Fondation", "Coopérative"] },
      { step: 1, key: "pays_intervention", label: "Pays / Zone d'intervention",   type: "text",     required: true },
      { step: 1, key: "experience",        label: "Expérience de l'organisation", type: "textarea", required: true, placeholder: "Ancienneté, secteurs d'intervention, projets passés..." },
      { step: 1, key: "bailleur",          label: "Bailleur de fonds ciblé",      type: "text",     required: true, placeholder: "UE, USAID, AFD, Banque Mondiale, PNUD..." },
      { step: 1, key: "appel_offres",      label: "Référence de l'appel à projets",type: "text" },
      { step: 2, key: "nom_projet",        label: "Titre du projet",              type: "text",     required: true },
      { step: 2, key: "problematique",     label: "Problématique principale",     type: "textarea", required: true, placeholder: "Décrivez le problème avec données, statistiques, exemples..." },
      { step: 2, key: "analyse_causes",    label: "Analyse des causes",           type: "textarea", required: true, placeholder: "Causes profondes, immédiates, sous-jacentes..." },
      { step: 2, key: "contexte_geo",      label: "Contexte géographique & socio-économique", type: "textarea", placeholder: "Population, indicateurs, situation politique, infrastructure..." },
      { step: 3, key: "objectif_general",  label: "Objectif général",             type: "textarea", required: true },
      { step: 3, key: "objectifs_specifiques",label: "Objectifs spécifiques (3-5)",type: "textarea", required: true, placeholder: "OS1: ...\nOS2: ...\nOS3: ..." },
      { step: 3, key: "resultats_attendus",label: "Résultats attendus",           type: "textarea", required: true, placeholder: "Pour chaque OS, les résultats concrets et mesurables attendus..." },
      { step: 3, key: "indicateurs",       label: "Indicateurs de succès (SMART)",type: "textarea", required: true, placeholder: "Indicateurs quantitatifs et qualitatifs pour chaque résultat..." },
      { step: 4, key: "activites",         label: "Activités par objectif",       type: "textarea", required: true, placeholder: "OS1 - Activité 1.1: ...\nActivité 1.2: ...\nOS2 - Activité 2.1: ..." },
      { step: 4, key: "methodologie",      label: "Méthodologie & Approche",      type: "textarea", required: true, placeholder: "Comment allez-vous mettre en œuvre ? Approche participative, genre, droits..." },
      { step: 4, key: "chronogramme",      label: "Chronogramme (mois par activité)",type: "textarea", required: true, placeholder: "Activité 1.1: Mois 1-2, Activité 1.2: Mois 2-4..." },
      { step: 5, key: "beneficiaires_directs",label: "Bénéficiaires directs",    type: "textarea", required: true, placeholder: "Nombre, profil, comment ils ont été sélectionnés..." },
      { step: 5, key: "beneficiaires_indirects",label: "Bénéficiaires indirects",type: "textarea" },
      { step: 5, key: "partenaires",       label: "Partenaires de mise en œuvre", type: "textarea", required: true, placeholder: "Gouvernement, collectivités, ONG partenaires, secteur privé..." },
      { step: 6, key: "budget_total",      label: "Budget total (EUR ou USD)",    type: "text",     required: true },
      { step: 6, key: "repartition_budget",label: "Répartition du budget par poste",type: "textarea",required: true, placeholder: "Personnel: X%, Activités: Y%, Équipements: Z%, Frais généraux: W%..." },
      { step: 6, key: "cofinancement",     label: "Cofinancement / Contribution propre",type: "textarea", placeholder: "Part cofinancée par l'organisation, % et montant..." },
      { step: 7, key: "systeme_suivi",     label: "Système de suivi-évaluation",  type: "textarea", required: true, placeholder: "Outils, fréquence des rapports, qui fait le suivi, données collectées..." },
      { step: 7, key: "risques_mitigation",label: "Risques & Mitigation",         type: "textarea", required: true, placeholder: "Risques programmatiques, financiers, contextuels et mesures d'atténuation..." },
      { step: 8, key: "durabilite",        label: "Durabilité / Pérennité post-projet",type: "textarea",required: true, placeholder: "Comment les résultats seront-ils maintenus après la fin du financement ?" },
      { step: 8, key: "integration_genre", label: "Intégration du genre & inclusion",type: "textarea", placeholder: "Comment le projet prend en compte l'égalité de genre..." },
      { step: 8, key: "infos_complementaires",label: "Informations complémentaires",type: "textarea" },
    ],
  },

  // ─── ACADÉMIQUE ─────────────────────────────────────────────────────────────
  {
    id: "rapport_stage",
    category: "academique",
    title: "Rapport de Stage",
    description: "Rapport de stage professionnel structuré et complet.",
    priceFcfa: 11175,
    icon: "GraduationCap",
    steps: [
      { number: 1, title: "Étudiant & Formation" },
      { number: 2, title: "Entreprise d'accueil" },
      { number: 3, title: "Missions & Activités" },
      { number: 4, title: "Analyse & Résultats" },
      { number: 5, title: "Bilan & Conclusion" },
    ],
    fields: [
      { step: 1, key: "full_name",         label: "Nom & Prénom",                 type: "text",     required: true },
      { step: 1, key: "ecole",             label: "École / Université",           type: "text",     required: true },
      { step: 1, key: "filiere",           label: "Filière / Spécialité",         type: "text",     required: true },
      { step: 1, key: "niveau",            label: "Niveau d'études",              type: "select",   options: ["Licence 1", "Licence 2", "Licence 3", "Master 1", "Master 2", "BTS", "DUT", "Ingénieur"] },
      { step: 1, key: "annee_academique",  label: "Année académique",             type: "text",     placeholder: "2024-2025" },
      { step: 1, key: "encadrant_ecole",   label: "Encadrant académique",         type: "text",     placeholder: "Nom du professeur référent" },
      { step: 2, key: "entreprise",        label: "Entreprise d'accueil",         type: "text",     required: true },
      { step: 2, key: "secteur_entreprise",label: "Secteur de l'entreprise",      type: "text",     required: true },
      { step: 2, key: "ville_pays",        label: "Ville, Pays",                  type: "text",     required: true },
      { step: 2, key: "poste_mission",     label: "Poste / Intitulé de la mission",type: "text",    required: true },
      { step: 2, key: "encadrant_pro",     label: "Maître de stage (nom, poste)", type: "text",     required: true },
      { step: 2, key: "duree_stage",       label: "Durée du stage",               type: "text",     required: true, placeholder: "Ex: 3 mois, du 01/06 au 31/08/2025" },
      { step: 2, key: "description_entreprise",label: "Présentation de l'entreprise",type: "textarea",required: true, placeholder: "Activité, taille, historique, organisation, position sur le marché..." },
      { step: 3, key: "missions_principales",label: "Missions principales confiées",type: "textarea",required: true, placeholder: "Listez et décrivez chaque mission..." },
      { step: 3, key: "activites_quotidiennes",label: "Activités quotidiennes",   type: "textarea", placeholder: "Tâches récurrentes, réunions, outils utilisés..." },
      { step: 3, key: "projets_realises",  label: "Projets ou tâches réalisés",   type: "textarea", required: true, placeholder: "Projets spécifiques menés, avec contexte, méthode, résultat..." },
      { step: 3, key: "outils_utilises",   label: "Outils & Logiciels utilisés",  type: "textarea", placeholder: "Excel, Sage, AutoCAD, Python, ERP, CRM..." },
      { step: 4, key: "competences_acquises",label: "Compétences acquises",       type: "textarea", required: true, placeholder: "Techniques, relationnelles, sectorielles..." },
      { step: 4, key: "difficultes_rencontrees",label: "Difficultés rencontrées & solutions",type: "textarea", placeholder: "Problèmes, obstacles, comment vous les avez surmontés..." },
      { step: 4, key: "apport_au_service", label: "Votre apport à l'entreprise",  type: "textarea", placeholder: "Ce que vous avez apporté : idées, améliorations, résultats..." },
      { step: 5, key: "bilan_personnel",   label: "Bilan personnel",              type: "textarea", required: true, placeholder: "Ce que vous retenez, évolution personnelle et professionnelle..." },
      { step: 5, key: "lien_cours",        label: "Lien avec les cours",          type: "textarea", required: true, placeholder: "Comment le stage a confirmé ou enrichi vos connaissances théoriques..." },
      { step: 5, key: "recommandations",   label: "Recommandations à l'entreprise",type: "textarea", placeholder: "Suggestions d'amélioration basées sur votre observation..." },
      { step: 5, key: "projet_professionnel",label: "Projet professionnel post-stage",type: "textarea", placeholder: "Où cela vous mène-t-il dans votre parcours ?" },
    ],
  },

  {
    id: "bourse",
    category: "academique",
    title: "Dossier de Bourse",
    description: "Dossier complet pour candidature à une bourse d'études ou d'excellence.",
    priceFcfa: 7425,
    badge: "Nouveau",
    icon: "Award",
    steps: [
      { number: 1, title: "Candidat & Situation" },
      { number: 2, title: "Parcours académique" },
      { number: 3, title: "Programme visé" },
      { number: 4, title: "Projet académique & professionnel" },
      { number: 5, title: "Motivation & Engagement" },
    ],
    fields: [
      { step: 1, key: "full_name",         label: "Nom complet",                  type: "text",     required: true },
      { step: 1, key: "date_naissance",    label: "Date de naissance",            type: "text",     required: true },
      { step: 1, key: "nationalite",       label: "Nationalité",                  type: "text",     required: true },
      { step: 1, key: "email",             label: "Email",                        type: "text",     required: true },
      { step: 1, key: "telephone",         label: "Téléphone",                    type: "text" },
      { step: 1, key: "situation_actuelle",label: "Situation actuelle",           type: "select",   options: ["Étudiant", "Jeune diplômé", "Professionnel en activité", "En recherche d'emploi"] },
      { step: 1, key: "situation_familiale",label: "Situation familiale & financière",type: "textarea", placeholder: "Taille de la famille, revenus des parents, situation socio-économique si pertinent..." },
      { step: 2, key: "formation_actuelle",label: "Formation / Diplôme actuel",   type: "textarea", required: true, placeholder: "Niveau, filière, université, pays, mention..." },
      { step: 2, key: "resultats_academiques",label: "Résultats académiques",     type: "textarea", required: true, placeholder: "Moyennes, classement, mentions, matières fortes..." },
      { step: 2, key: "formations_anterieures",label: "Formations antérieures",   type: "textarea", placeholder: "Diplômes précédents, certifications, formations courtes..." },
      { step: 2, key: "distinctions",      label: "Distinctions & Prix",          type: "textarea", placeholder: "Prix d'excellence, félicitations du jury, concours gagnés..." },
      { step: 3, key: "programme_bourse",  label: "Nom de la bourse / Programme", type: "text",     required: true, placeholder: "Ex: Bourse d'excellence EIFFEL, DAAD, AFD Bourses..." },
      { step: 3, key: "bailleur_bourse",   label: "Organisme accordant la bourse",type: "text",     required: true },
      { step: 3, key: "formation_visee",   label: "Formation visée",              type: "text",     required: true, placeholder: "Master en Finance, Doctorat en Santé publique..." },
      { step: 3, key: "etablissement_cible",label: "Établissement d'accueil visé",type: "text",     placeholder: "Université de Paris, Harvard, UCL..." },
      { step: 3, key: "pays_etude",        label: "Pays d'études",                type: "text",     required: true },
      { step: 3, key: "duree",             label: "Durée du programme",           type: "text",     placeholder: "2 ans, 3 ans..." },
      { step: 4, key: "projet_recherche",  label: "Projet de recherche / mémoire",type: "textarea", placeholder: "Sujet envisagé, problématique, méthodologie (pour Doctorat/Master recherche)..." },
      { step: 4, key: "projet_professionnel",label: "Projet professionnel à l'issue",type: "textarea",required: true, placeholder: "Où voulez-vous travailler / ce que vous voulez accomplir après vos études ?" },
      { step: 4, key: "retour_pays",       label: "Plan de retour au pays",       type: "textarea", placeholder: "Comment comptez-vous contribuer à votre pays après vos études ?" },
      { step: 5, key: "motivation",        label: "Lettre de motivation",         type: "textarea", required: true, placeholder: "Pourquoi cette bourse ? Pourquoi cette formation ? Pourquoi vous ?" },
      { step: 5, key: "engagement_social", label: "Engagements sociaux & associatifs", type: "textarea", placeholder: "Bénévolat, associations, projets communautaires, leadership..." },
      { step: 5, key: "experiences_internationales",label: "Expériences internationales",type: "textarea", placeholder: "Séjours à l'étranger, échanges, formations internationales..." },
      { step: 5, key: "langues",           label: "Langues maîtrisées",           type: "textarea", required: true, placeholder: "Français C2, Anglais B2, Allemand A2..." },
    ],
  },
];

export function getServiceById(id: string): Service | undefined {
  return SERVICES.find((s) => s.id === id);
}

export function getServicesByCategory(category: ServiceCategory): Service[] {
  return SERVICES.filter((s) => s.category === category);
}
